# Generated by Django 5.1.2 on 2024-10-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_eventspipe', '0005_alter_eventschedule_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelineartifact',
            options={'verbose_name': 'Artifact', 'verbose_name_plural': 'Artifacts'},
        ),
    ]
